alias ea='nvim ~/.bash_aliases; source ~/.bash_aliases && echo "aliases sourced  --ok."'
alias hsh="cd /home/alx/c/simple_shell"
alias dcc="gcc -Wall -Werror -Wextra -pedantic -std=gnu89"
alias add='git add'
alias com='git commit -m'
alias push='git push'
alias tcn='mv --force -t ~/.local/share/Trash '
alias bashrc='nvim ~/.bashrc'
alias load-bash='source ~/.bashrc'
alias load-aliases='source ~/.bash_aliases'
alias vivi='vim ~/.vimrc'
alias ..='cd ..'
alias null='/dev/null'
alias status='git status'
alias proj="cd /home/abuahmad/my_projects/c_proj/testing"
alias copy-tmp="cat /tmp/tmp | clip.exe"
alias nv='nvim'
alias nv-init='nvim ~/.config/nvim/init.vim'
alias pycodestyle='pycodestyle --show-source'
alias pcs='pycodestyle --show-source'
alias chmx='chmod +x'
alias pull='git pull'
alias see="explorer.exe"
alias wp="pclip > /tmp/vim-wp && nv /tmp/vim-wp && clip /tmp/vim-wp"
alias todo='nvim ~/.todo '
alias lg='lazygit'
alias rm='mv --force -t ~/.local/share/Trash '
alias mathml2latex='pandoc -f html --mathml -t latex'
